name: 'Deploy static files to s3 '
description: 'Deploy your static files to s3 in record time'
inputs:
  bucketName:
    description: 'Name of the bucket where files are to be deployed'
    required: true
  distributionFolder: 
    description: 'Name of the folder Where build is kept'
    required: true
    default: 'build'
  indexDocument: 
    description: 'Name of the index Document to set to bucket'
    required: true
    default: 'index.html'
  errorDocument: 
    description: 'Name of the file to display during error'
    required: true
    default: 'error.html'

outputs:
  time: # id of output
    description: 'The time we greeted you'
runs:
  using: 'node12'
  main: 'index.js'