on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
    - name: Hello world action step
      id: hello
      uses: rtgstudio/aws-s3-deploy@master
      with:
        bucketName: 'Mona the Octocat'
        distributionFolder: 'Mona the Octocat'
        indexDocument: 'Mona the Octocat'
        errorDocument: 'Mona the Octocat'
    # Use the output from the `hello` step
    - name: Get the output time
      run: echo "The time was ${{ steps.hello.outputs.time }}"